#!/usr/bin/env python3
"""Compile markdown tables in docs/design/ into data/*.json.

The documentation is the source of truth; these JSON files are its projection.
Never hand-edit a generated file -- `make check` regenerates and diffs.

A table is compiled when preceded by:

    <!-- generates: data/curriculum.json -->

See docs/decisions/0006-docs-are-canonical.md
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MARKER = re.compile(r"<!--\s*generates:\s*(\S+)\s*-->")
NONE_TOKENS = {"", "—", "-", "–", "n/a"}


def slug(header: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "_", header.strip().lower()).strip("_")
    return s


def clean(cell: str) -> str | None:
    v = cell.strip().strip("`").strip()
    return None if v.lower() in NONE_TOKENS else v


def number(v: str):
    try:
        return int(v)
    except ValueError:
        return float(v)


def parse_tables(path: Path) -> dict[str, list[dict]]:
    """Return {target_path: rows} for every marked table in a doc."""
    out: dict[str, list[dict]] = {}
    lines = path.read_text(encoding="utf-8").splitlines()
    i = 0
    while i < len(lines):
        m = MARKER.search(lines[i])
        if not m:
            i += 1
            continue
        target = m.group(1)
        # advance to the header row of the next table
        j = i + 1
        while j < len(lines) and not lines[j].lstrip().startswith("|"):
            if lines[j].strip() and not lines[j].startswith("<!--"):
                raise SystemExit(
                    f"{path}: 'generates: {target}' is not followed by a table"
                )
            j += 1
        if j >= len(lines):
            raise SystemExit(f"{path}: 'generates: {target}' has no table")
        headers = [slug(c) for c in lines[j].strip().strip("|").split("|")]
        j += 2  # skip the |---|---| separator
        rows = []
        while j < len(lines) and lines[j].lstrip().startswith("|"):
            cells = [clean(c) for c in lines[j].strip().strip("|").split("|")]
            if len(cells) != len(headers):
                raise SystemExit(
                    f"{path}:{j+1}: row has {len(cells)} cells, header has {len(headers)}"
                )
            rows.append(dict(zip(headers, cells)))
            j += 1
        out[target] = rows
        i = j
    return out


# --- per-target shaping -----------------------------------------------------

def shape_tuning(rows):
    values, meta = {}, {}
    for r in rows:
        values[r["key"]] = number(r["value"])
        meta[r["key"]] = {"unit": r["unit"], "description": r["what_it_does"]}
    return {"values": values, "meta": meta}


def shape_curriculum(rows):
    stages, cumulative = [], []
    for r in rows:
        keys = r["keys"].split()
        cumulative = cumulative + [k for k in keys if k not in cumulative]
        stages.append({
            "stage": int(r["stage"]),
            "keys": keys,
            "keySet": list(cumulative),
            "predictedCoverage": float(r["coverage"]),
            "description": r["description"],
        })
    return {"stages": stages}


def shape_route(rows):
    return {"id": "pilgrimage", "edges": rows}


def shape_scenes(rows):
    return {"text": "bible", "scenes": rows}


def shape_list(key):
    return lambda rows: {key: rows}


SHAPERS = {
    "data/tuning.json": shape_tuning,
    "data/curriculum.json": shape_curriculum,
    "data/routes/pilgrimage.json": shape_route,
    "data/scenes/bible.json": shape_scenes,
    "data/items.json": shape_list("items"),
    "data/themes.json": shape_list("themes"),
}


def build() -> dict[str, str]:
    """Return {target_path: json_text} for everything the docs define."""
    generated: dict[str, str] = {}
    for doc in sorted((ROOT / "docs" / "design").glob("*.md")):
        for target, rows in parse_tables(doc).items():
            if target in generated:
                raise SystemExit(f"{target} is generated by two documents")
            shaper = SHAPERS.get(target)
            if shaper is None:
                raise SystemExit(
                    f"{doc}: no shaper registered for '{target}'. "
                    f"Add one to tools/build_from_docs.py."
                )
            payload = shaper(rows)
            payload["_generated_from"] = str(doc.relative_to(ROOT))
            generated[target] = json.dumps(payload, indent=2, ensure_ascii=False) + "\n"
    return generated


def main() -> int:
    check_only = "--check" in sys.argv
    generated = build()
    if not generated:
        print("no generating tables found", file=sys.stderr)
        return 1
    stale = []
    for target, text in sorted(generated.items()):
        path = ROOT / target
        if check_only:
            if not path.exists() or path.read_text(encoding="utf-8") != text:
                stale.append(target)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
    if check_only and stale:
        print("Generated data is out of date with the docs:", file=sys.stderr)
        for t in stale:
            print(f"  {t}", file=sys.stderr)
        print("\nRun `make build`. Never hand-edit generated files.", file=sys.stderr)
        return 1
    if not check_only:
        print(f"generated {len(generated)} file(s) from docs/design/")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
